/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Finding total customers by countries
SELECT
    country,
	COUNT(customer_key) AS total_customers
FROM gold2.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Finding total customers by gender
SELECT 
	gender,
    COUNT(customer_key) AS total_customers
FROM gold2.dim_customers
GROUP BY gender;

-- Finding total products by category
SELECT 
	category,
    COUNT(product_key) AS total_products
FROM gold2.dim_products
GROUP BY category;

-- What is the average cost in each category?
SELECT
	category,
    AVG(product_cost) AS average_cost
FROM gold2.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    dp.category,
	SUM(fs.sales) AS total_revenue
FROM gold2.fact_sales AS fs
LEFT JOIN gold2.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY category;

-- Finding total revenue is generated by each customer
SELECT
    dc.customer_key,
    dc.first_name,
    dc.last_name,
	SUM(fs.sales) AS total_revenue
FROM gold2.fact_sales AS fs
LEFT JOIN gold2.dim_customers AS dc
USING(customer_key)
GROUP BY fs.customer_key, dc.first_name, dc.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT 
	dc.country,
    SUM(fs.quantity) AS total_sold_items
FROM gold2.fact_sales AS fs
LEFT JOIN gold2.dim_customers AS dc
USING(customer_key)
GROUP BY dc.country
ORDER BY total_sold_items DESC;
